---
sudo:     false
language: ruby
cache:    bundler
before_install:
  - gem update --system
  - gem uninstall -v '>= 1' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v 1.3.0
  - gem update --system
script:
  - bundle exec rake
rvm:
  - 2.3
  - 2.6
  - ruby-head
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4.2.gemfile
  allow_failures:
    - rvm: ruby-head
